on: [push]
name: 'CI'
jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.7.5
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - run: yarn lerna bootstrap
      - run: yarn lint
      - run: yarn tsc
      - run: yarn clean
      - run: yarn build
      - run: yarn test
